version: '3'

services:

  neo4j:
    image: neo4j:latest
    container_name: icebreaker_neo4j
    volumes:
      - ./data:/data
      - ./logs:/logs
      - ./conf:/var/lib/neo4j/conf
      - ./plugins:/var/lib/neo4j/plugins
      - ./import:/var/lib/neo4j/import
    ports:
      - 127.0.0.1:7474:7474
      - 127.0.0.1:7687:7687
    environment:
      NEO4J_AUTH: neo4j/elsa
