version: '3'
services:
  postgres:
    image: postgres:12
    container_name: icebreaker_network_postgres
    restart: unless-stopped
    ports:
      - 127.0.0.1:12210:5432
    environment:
      - POSTGRES_DB=icebreaker_network
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
