version: '3'
services:

  jupyter:
    image: jupyter/scipy-notebook
    container_name: icebreaker_network_jupyter
    command: start.sh jupyter lab
    volumes:
      - ./notebook:/home/jovyan/notebook
      - ./src:/home/jovyan/src
      - ./data:/home/jovyan/data
    ports:
      - 127.0.0.1:12200:8888
